    name: Deploy Frontend
    on:
        push:
            branches: [ "master" ]
  
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dkrtst -f Dockerfile.dev .
          - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/dkrtst npm test
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: dkr_tst
              environment_name: Dkrtst-env
              existing_bucket_name: elasticbeanstalk-eu-central-1-599028203858
              region: eu-central-1
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip